service: site-asso-infra
frameworkVersion: '4'

org: wolfcorp
app: site-asso

provider:
  name: aws
  region: eu-west-3
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    AssoMainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: site-asso-${sls:stage}-asso-main
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - { AttributeName: PK,   AttributeType: S }
          - { AttributeName: SK,   AttributeType: S }
          - { AttributeName: GSI1, AttributeType: S }   # email
          - { AttributeName: GSI2, AttributeType: S }   # jti
        KeySchema:
          - { AttributeName: PK, KeyType: HASH }
          - { AttributeName: SK, KeyType: RANGE }
          
        GlobalSecondaryIndexes:
        
          - IndexName: GSI1
            KeySchema:
              - { AttributeName: GSI1, KeyType: HASH }
              - { AttributeName: SK,   KeyType: RANGE }
            Projection: { ProjectionType: ALL }

          - IndexName: GSI2
            KeySchema:
              - { AttributeName: GSI2, KeyType: HASH }
              - { AttributeName: SK,   KeyType: RANGE }
            Projection: { ProjectionType: ALL }

        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: true

    AssoAuthTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: site-asso-${sls:stage}-asso-auth-v2
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - { AttributeName: PK, AttributeType: S }   # EMAIL#<email>
          - { AttributeName: SK, AttributeType: S }   # AUTH
          - { AttributeName: GSI1PK, AttributeType: S }   # USER#<userId>
          - { AttributeName: GSI1SK, AttributeType: S }
        KeySchema:
          - { AttributeName: PK, KeyType: HASH }
          - { AttributeName: SK, KeyType: RANGE }
        GlobalSecondaryIndexes:
          - IndexName: GSI1v2
            KeySchema:
              - { AttributeName: GSI1PK, KeyType: HASH }
              - { AttributeName: GSI1SK, KeyType: RANGE }
            Projection: 
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - PK
                - SK
                - userId
                - createdAt

          - IndexName: GSI1v5
            KeySchema:
              - { AttributeName: GSI1PK, KeyType: HASH }
              - { AttributeName: GSI1SK, KeyType: RANGE }
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - passwordHash
                - userId
                - roles

          - IndexName: GSI1v6
            KeySchema:
              - { AttributeName: GSI1PK, KeyType: HASH }
              - { AttributeName: GSI1SK, KeyType: RANGE }
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - passwordHash
                - userId
                - privilege
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    RateLimitTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: site-asso-${sls:stage}-rate-limit
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - { AttributeName: PK, AttributeType: S } #RL#IP#xxx.x.xxx.x/RL#USER#xxxxxxxxxxx
        KeySchema:
          - { AttributeName: PK, KeyType: HASH }
        TimeToLiveSpecification:
          AttributeName: expiredAt
          Enabled: true

    TokenTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: site-asso-${sls:stage}-token
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - { AttributeName: PK, AttributeType: S } #TOKEN#xxxxxxxxxxxx
          - { AttributeName: SK, AttributeType: S } #TYPE#xxxx
        KeySchema:
          - { AttributeName: PK, KeyType: HASH }
          - { AttributeName: SK, KeyType: RANGE }
        TimeToLiveSpecification:
          AttributeName: expiredAt
          Enabled: true

    EventBusSiteAssoRegister:
      Type: AWS::Events::EventBus
      Properties:
        Name: site-asso-event-bus-register-${sls:stage}

    KmsJwtSigningKey:
      Type: AWS::KMS::Key
      Properties:
        Description: "KMS key used to sign JWT access tokens for site-asso"
        KeySpec: RSA_2048
        KeyUsage: SIGN_VERIFY
        Enabled: true
        MultiRegion: false
        PendingWindowInDays: 7

    KmsJwtSigningAlias:
      Type: AWS::KMS::Alias
      Properties:
        AliasName: alias/site-asso-auth-${sls:stage}
        TargetKeyId: !Ref KmsJwtSigningKey

  Outputs:

    DdbUserTable:
      Value: !Ref AssoMainTable
      Export:
        Name: site-asso-infra-${sls:stage}-DdbUserTable
    DdbUserTableArn:
      Value: !GetAtt AssoMainTable.Arn
      Export:
        Name: site-asso-infra-${sls:stage}-DdbUserTableArn

    DdbAuthTableName:
      Value: !Ref AssoAuthTable
      Export:
        Name: site-asso-infra-${sls:stage}-DdbAuthTableName
    DdbAuthTableArn:
      Value: !GetAtt AssoAuthTable.Arn
      Export:
        Name: site-asso-infra-${sls:stage}-DdbAuthTableArn
    DdbAuthStreamArn:
      Value: !GetAtt AssoAuthTable.StreamArn
      Export:
        Name: site-asso-infra-${sls:stage}-DdbAuthStreamArn

    DdbRateLimitTable:
      Value: !Ref RateLimitTable
      Export:
        Name: site-asso-infra-${sls:stage}-DdbRateLimitTable
    DdbRateLimitTableArn:
      Value: !GetAtt RateLimitTable.Arn
      Export:
        Name: site-asso-infra-${sls:stage}-DdbRateLimitTableArn

    DdbTokenTable:
      Value: !Ref TokenTable
      Export:
        Name: site-asso-infra-${sls:stage}-DdbTokenTable
    DdbTokenTableArn:
      Value: !GetAtt TokenTable.Arn
      Export:
        Name: site-asso-infra-${sls:stage}-DdbTokenTableArn

    RegisterEventBusName:
      Value: !Ref EventBusSiteAssoRegister
      Export:
        Name: site-asso-infra-${sls:stage}-RegisterEventBusName
    RegisterEventBusArn:
      Value: !GetAtt EventBusSiteAssoRegister.Arn
      Export:
        Name: site-asso-infra-${sls:stage}-RegisterEventBusArn

    KmsJwtSigningKeyArn:
      Value: !GetAtt KmsJwtSigningKey.Arn
      Export:
        Name: site-asso-infra-${sls:stage}-KmsJwtSigningKeyArn