service: site-asso-api
frameworkVersion: '4'

org: wolfcorp
app: site-asso

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-west-3
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 12
  # httpApi:
  #   throttling:
  #     burstLimit: 50 #pics max
  #     rateLimit: 25 #req/s
  environment:
    # NODE_OPTIONS: '--enable-source-maps' # Pour activer les sourcemaps dans CloudWatch Logs à retirer dans la prod
    RUNTIME: 'lambda'
    USER_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbUserTable}
    AUTH_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbAuthTableName}
    PROJECT_AWS_REGION: ${self:provider.region}
    STAGE: ${sls:stage}
    JWT_ACCESS_PUB_SSM_PARAM: /site-asso/${sls:stage}/cfg/jwtAccessPub

plugins:
  # - ./backend/node_modules/serverless-esbuild

build:
  esbuild:
    bundle: true
    platform: node
    target: node22
    format: esm            
    sourcemap: true
    minify: false
    # external: []
    # mainFields:
    #   - module
    #   - main
    # banner:
    #   js: "import { createRequire } from 'module'; global.require = createRequire(import.meta.url);"

functions:
  registerUser:
    handler: backend/lambda/registerUserLambda.handler
    memorySize: 1024
    architecture: arm64
    environment:
      AUTH_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbAuthTableName}
      RATE_LIMIT_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbRateLimitTable}
      REGISTER_EVENT_BUS: ${cf:site-asso-infra-${sls:stage}.RegisterEventBusName}
      JWT_ACCESS_PUB_PEM: ${ssm:/site-asso/${sls:stage}/cfg/jwtAccessPub}
      KMS_JWT_KEY_ID: alias/site-asso-auth-${sls:stage}
      REFRESH_JWT_HMAC: ${ssm:/site-asso/${sls:stage}/secret/refreshTokenHmac}
      USER_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbUserTable}
      TOKEN_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbTokenTable}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:TransactWriteItems
        Resource:
          - ${cf:site-asso-infra-${sls:stage}.DdbAuthTableArn}

      - Effect: Allow
        Action:
          - kms:Sign
        Resource: ${cf:site-asso-infra-${sls:stage}.KmsJwtSigningKeyArn}

      - Effect: Allow
        Action:
          - events:PutEvents
        Resource: ${cf:site-asso-infra-${sls:stage}.RegisterEventBusArn}

      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: ${cf:site-asso-infra-${sls:stage}.DdbTokenTableArn}

      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:UpdateItem
        Resource: ${cf:site-asso-infra-${sls:stage}.DdbRateLimitTableArn}
    events:
      - httpApi: 
          method: PUT
          path: /registerUser

  loginUser:
    handler: backend/lambda/logInAuthUserLambda.handler
    memorySize: 1024
    architecture: arm64
    environment:
      AUTH_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbAuthTableName}
      RATE_LIMIT_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbRateLimitTable}
      JWT_ACCESS_PUB_PEM: ${ssm:/site-asso/${sls:stage}/cfg/jwtAccessPub}
      KMS_JWT_KEY_ID: alias/site-asso-auth-${sls:stage}
      USER_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbUserTable}
      REFRESH_JWT_HMAC: ${ssm:/site-asso/${sls:stage}/secret/refreshTokenHmac}
      TOKEN_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbTokenTable}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: 
          - ${cf:site-asso-infra-${sls:stage}.DdbAuthTableArn}
          - ${cf:site-asso-infra-${sls:stage}.DdbAuthTableArn}/index/*

      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: 
          - ${cf:site-asso-infra-${sls:stage}.DdbUserTableArn}

      - Effect: Allow
        Action:
          - kms:Sign
        Resource: ${cf:site-asso-infra-${sls:stage}.KmsJwtSigningKeyArn}
      
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:UpdateItem
        Resource: ${cf:site-asso-infra-${sls:stage}.DdbRateLimitTableArn}

      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: ${cf:site-asso-infra-${sls:stage}.DdbTokenTableArn}

    events:
      - httpApi:
          method: GET
          path: /login

  updateAuthUser:
    handler: backend/lambda/updateAuthUserLambda.handler
    memorySize: 1024
    architecture: arm64
    environment:
      AUTH_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbAuthTableName}
      RATE_LIMIT_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbRateLimitTable}
      JWT_ACCESS_PUB_PEM: ${ssm:/site-asso/${sls:stage}/cfg/jwtAccessPub}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:TransactWriteItems
        Resource:
          - ${cf:site-asso-infra-${sls:stage}.DdbAuthTableArn}
          - ${cf:site-asso-infra-${sls:stage}.DdbUserTableArn}

      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:UpdateItem
        Resource: ${cf:site-asso-infra-${sls:stage}.DdbRateLimitTableArn}

      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/site-asso/${sls:stage}/*

    events:
      - httpApi: 
          method: PATCH
          path: /updateUser

  updateAuthUserPassword:
    handler: backend/lambda/updateAuthUserPasswordLambda.handler
    memorySize: 1024
    architecture: arm64
    environment:
      AUTH_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbAuthTableName}
      RATE_LIMIT_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbRateLimitTable}
      JWT_ACCESS_PUB_PEM: ${ssm:/site-asso/${sls:stage}/cfg/jwtAccessPub}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
        Resource:
          - ${cf:site-asso-infra-${sls:stage}.DdbAuthTableArn}
          
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:UpdateItem
        Resource: ${cf:site-asso-infra-${sls:stage}.DdbRateLimitTableArn}

      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/site-asso/${sls:stage}/*
    events:
      - httpApi: 
          method: PATCH
          path: /updatePassword

  removeAuthUser:
    handler: backend/lambda/removeAuthUserLambda.handler
    memorySize: 1024
    architecture: arm64
    environment:
      AUTH_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbAuthTableName}
      JWT_ACCESS_PUB_PEM: ${ssm:/site-asso/${sls:stage}/cfg/jwtAccessPub}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
        Resource:
          - ${cf:site-asso-infra-${sls:stage}.DdbAuthTableArn}

      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/site-asso/${sls:stage}/*
    events:
      - httpApi:
          method: DELETE
          path: /removeAuthUser

  refreshAuthUser:
    handler: backend/lambda/refreshAuthUserLambda.handler
    memorySize: 1024
    architecture: arm64
    environment:
      TOKEN_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbTokenTable}
      REFRESH_JWT_HMAC: ${ssm:/site-asso/${sls:stage}/secret/refreshTokenHmac}
      USER_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbUserTable}
    iamRoleStatements:
      
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: 
          - ${cf:site-asso-infra-${sls:stage}.DdbUserTableArn}

      - Effect: Allow
        Action:
          - kms:Sign
        Resource: ${cf:site-asso-infra-${sls:stage}.KmsJwtSigningKeyArn}

    events:
      - httpApi:
          method: POST
          path: /refresh
          
  onRegisterAuth: #Ajout de nouveau user dans la table générale des users
    handler: backend/lambda/onRegisterAuthLambda.handler
    memorySize: 1024              # 1024–1536 Mo pour marge CPU
    architecture: arm64           # ARM64 conseillé
    timeout: 30
    environment:
      USER_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbUserTable}
    events:
      - eventBridge:
          eventBus: ${cf:site-asso-infra-${sls:stage}.RegisterEventBusArn}
          pattern:
            source:
              - site-asso.auth.register
            detail-type:
              - UserRegistered
          deadLetterQueueArn:
            Fn::GetAtt: 
              - RegisterEventDLQ
              - Arn
          retryPolicy:
            maximumRetryAttempts: 3
            maximumEventAgeInSeconds: 3600
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:TransactWriteItems
          - dynamodb:ConditionCheckItem
        Resource:
          - ${cf:site-asso-infra-${sls:stage}.DdbUserTableArn}

  onRemoveAuthUserStream: #suppression de user dans la table générale des users
    handler: backend/lambda/onRemoveAuthStreamLambda.handler
    architecture: arm64           # ARM64 conseillé
    memorySize: 1024              # 1024–1536 Mo pour marge CPU
    timeout: 30
    environment:
      USER_TABLE: ${cf:site-asso-infra-${sls:stage}.DdbUserTable}
    events:
      - stream:
          type: dynamodb
          arn: ${cf:site-asso-infra-${sls:stage}.DdbAuthStreamArn}  # <- Output ARN du stream
          batchSize: 10
          startingPosition: LATEST
          maximumRetryAttempts: 3
          bisectBatchOnFunctionError: true
          destinations:
            onFailure:
              type: sqs
              arn:
                Fn::GetAtt: [ AuthStreamDLQ, Arn ]
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
          - dynamodb:TransactWriteItems
          - dynamodb:ConditionCheckItem
        Resource:
          - ${cf:site-asso-infra-${sls:stage}.DdbUserTableArn}

      - Effect: Allow
        Action:
          - sqs:SendMessage
          - sqs:GetQueueAttributes
        Resource:
          - Fn::GetAtt: [ AuthStreamDLQ, Arn ]

resources:
  Resources:
    AuthStreamDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${sls:stage}-authstream-dlq

    RegisterEventDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${sls:stage}-register-event-dlq

package:
  patterns:
    - '!backend/tests/**'
    - 'package.json'
    - 'backend/package.json'

