service: site-asso-infra
frameworkVersion: '4'

org: wolfcorp
app: site-asso

provider:
  name: aws
  region: eu-west-3
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    AssoMainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: site-asso-${sls:stage}-asso-main
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - { AttributeName: PK,   AttributeType: S }
          - { AttributeName: SK,   AttributeType: S }
          - { AttributeName: GSI1, AttributeType: S }   # email
          - { AttributeName: GSI2, AttributeType: S }   # jti
        KeySchema:
          - { AttributeName: PK, KeyType: HASH }
          - { AttributeName: SK, KeyType: RANGE }
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - { AttributeName: GSI1, KeyType: HASH }
              - { AttributeName: SK,   KeyType: RANGE }
            Projection: { ProjectionType: ALL }
          - IndexName: GSI2
            KeySchema:
              - { AttributeName: GSI2, KeyType: HASH }
              - { AttributeName: SK,   KeyType: RANGE }
            Projection: { ProjectionType: ALL }
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: true

    AssoAuthTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: site-asso-${sls:stage}-asso-auth-v2
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - { AttributeName: PK, AttributeType: S }   # EMAIL#<email>
          - { AttributeName: SK, AttributeType: S }   # AUTH
          - { AttributeName: GSI1PK, AttributeType: S }   # USER#<userId>
          - { AttributeName: GSI1SK, AttributeType: S }
        KeySchema:
          - { AttributeName: PK, KeyType: HASH }
          - { AttributeName: SK, KeyType: RANGE }
        GlobalSecondaryIndexes:
          - IndexName: GSI1v2
            KeySchema:
              - { AttributeName: GSI1PK, KeyType: HASH }
              - { AttributeName: GSI1SK,   KeyType: RANGE }
            Projection: 
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - PK
                - SK
                - userId
                - passwordHash
                - createdAt
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    RateLimitTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: site-asso-${sls:stage}-rate-limit
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - { AttributeName: PK, AttributeType: S } #RL#IP#xxx.x.xxx.x/RL#USER#xxxxxxxxxxx
        KeySchema:
          - { AttributeName: PK, KeyType: HASH }
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: true

  Outputs:

    DdbUserTable:
      Value: !Ref AssoMainTable
      Export:
        Name: site-asso-infra-${sls:stage}-DdbUserTable
    DdbUserTableArn:
      Value: !GetAtt AssoMainTable.Arn
      Export:
        Name: site-asso-infra-${sls:stage}-DdbUserTableArn

    DdbAuthTableName:
      Value: !Ref AssoAuthTable
      Export:
        Name: site-asso-infra-${sls:stage}-DdbAuthTableName
    DdbAuthTableArn:
      Value: !GetAtt AssoAuthTable.Arn
      Export:
        Name: site-asso-infra-${sls:stage}-DdbAuthTableArn
    DdbAuthStreamArn:
      Value: !GetAtt AssoAuthTable.StreamArn
      Export:
        Name: site-asso-infra-${sls:stage}-DdbAuthStreamArn

    DdbRateLimitTable:
      Value: !Ref RateLimitTable
      Export:
        Name: site-asso-infra-${sls:stage}-DdbRateLimitTable
    DdbRateLimitTableArn:
      Value: !GetAtt RateLimitTable.Arn
      Export:
        Name: site-asso-infra-${sls:stage}-DdbRateLimitTableArn
