name: CI/CD site-asso API

on:
  push:
    branches:
      - master
      - dev
      - feature/**
    paths:
      - 'backend/**'
      - 'serverless.api.yml'
      - 'serverless.infra.yml'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'backend/**'
      - 'serverless.api.yml'
      - 'serverless.infra.yml'

concurrency:
  group: site-asso-api-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # test:
  #   name: Lint & tests backend
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Use Node.js 22
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '22'
  #         cache: 'npm'
  #         cache-dependency-path: |
  #           backend/package-lock.json

  #     - name: Install backend dependencies
  #       working-directory: ./backend
  #       run: npm ci

  #     - name: Run unit tests
  #       working-directory: ./backend
  #       run: npm run test:unit

  deploy-infra:
    name: Deploy Infra
    # needs: setup-aws
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      id-token: write      # pour l'OIDC vers AWS
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set STAGE from branch
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "Current branch: $BRANCH"

          if [ "$BRANCH" = "master" ]; then
            echo "STAGE=prod" >> $GITHUB_ENV
          elif [ "$BRANCH" = "dev" ]; then
            echo "STAGE=dev" >> $GITHUB_ENV
          else
            # feature/*
            echo "STAGE=sandbox" >> $GITHUB_ENV
          fi

      - name: Cache Serverless build
        uses: actions/cache@v4
        with:
          path: .serverless
          key: ${{ runner.os }}-serverless-${{ hashFiles('serverless.infra.yml', 'serverless.api.yml') }}

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-3
          role-to-assume: arn:aws:iam::011664843444:role/github_pipeline_access
          role-session-name: site-asso-ci

      - name: Debug - config Serverless compilée
        working-directory: .
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          npx serverless print --config serverless.infra.yml --stage $STAGE | sed -n '1,200p'

      - name: Deploy Infra
        working-directory: .
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          npx serverless deploy --config serverless.infra.yml --stage $STAGE

  deploy-api:
    name: Deploy API
    needs: deploy-infra
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      id-token: write      # pour l'OIDC vers AWS
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set STAGE from branch
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "Current branch: $BRANCH"

          if [ "$BRANCH" = "master" ]; then
            echo "STAGE=prod" >> $GITHUB_ENV
          elif [ "$BRANCH" = "dev" ]; then
            echo "STAGE=dev" >> $GITHUB_ENV
          else
            # feature/*
            echo "STAGE=sandbox" >> $GITHUB_ENV
          fi

      - name: Cache Serverless build
        uses: actions/cache@v4
        with:
          path: .serverless
          key: ${{ runner.os }}-serverless-${{ hashFiles('serverless.infra.yml', 'serverless.api.yml') }}

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-3
          role-to-assume: arn:aws:iam::011664843444:role/github_pipeline_access
          role-session-name: site-asso-ci

      - name: Deploy API
        working-directory: .
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          npx serverless deploy --config serverless.api.yml --stage $STAGE

  integration-tests:
    name: Integration tests
    needs: 
      - deploy-api
    runs-on: ubuntu-latest

    permissions:
      id-token: write      # pour l'OIDC vers AWS
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set STAGE from branch
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "Current branch: $BRANCH"

          if [ "$BRANCH" = "master" ]; then
            echo "STAGE=prod" >> $GITHUB_ENV
          elif [ "$BRANCH" = "dev" ]; then
            echo "STAGE=dev" >> $GITHUB_ENV
          else
            # feature/*
            echo "STAGE=sandbox" >> $GITHUB_ENV
          fi

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-3
          role-to-assume: arn:aws:iam::011664843444:role/github_pipeline_access
          role-session-name: site-asso-ci

      - name: Run integration tests
        working-directory: ./backend
        run: |
          npm run test:integration